### ISSUE TITLE
possible to create a portable app version?

### ISSUE THREAD

**Issue by sfthurber** [meteor/meteor-chocolatey-installer#13]
possible to create a portable app version?

this would be super-useful.

put it on a usb stick and use it anywhere.

**Comment by abernix** [comment]
I'm not sure how this relates to this repository.  Some additional clarity would be helpful when opening this, especially in terms of exactly what you're trying to accomplish.  For example: trying to install the `meteor` tool from a USB stick, or trying to run an application itself.

A bundled app is more than capable of being portable, assuming it requires no network activity to run.  The installer is a completely different story and unfortunately, since Meteor needs to be able to connect to the internet to communicate with its package server after installation, isn't a viable option.

All in all, this seems like it would be a feature request, so it should go over here: https://github.com/meteor/meteor-feature-requests/issues/new.
