### ISSUE TITLE
[Workaround found] Cannot install non-admin version of Window 64 bit meteor

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor-chocolatey-installer#2]
Was [meteor #9288](https://github.com/meteor/meteor/issues/9288)

I cannot figure out how to install a non-admin version of Windows 64 bit meteor.

### Environment
- Windows 10 1703 (OS Build 15063.674)

### Attempts
Installed `chocolately` as instructed here: https://chocolatey.org/install using `cmd` window.

#### Attempt 1
1. Tried simply running `choco install meteor` from a non-admin window.  Was notified by `chocolately` that I could not install in a non-admin window.

#### Attempt 2
1. open a  `cmd` window with "run as administrator"
2. `choco install meteor`
3. open regular `cmd ` window
4. `meteor create t64`
5. `cd t64`
6.
```
meteor node
>process
...
arch: 'ia32',
```
I looked at the install at `C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool` and I found this folder `mt-os.windows.x86_32` which implied 32 bit.

#### Attempt 3
1. `choco uninstall meteor`
2. move `C:\Users\Bruce\AppData\Local\.meteor` to `C:\Users\Bruce\AppData\Local\.meteorOLD`
3. open a  `cmd` window with "run as administrator"
4. `choco install meteor`
5. open regular `cmd` window
6. `meteor`

**Result:** `'meteor' is not recognized as an internal or external command,
operable program or batch file.`  Meteor is only installed at `C:\Users\admin\AppData\Local\.meteor`

#### Attempt 4
1. `choco uninstall meteor`
2. cleaned up `C:\Users\Bruce\AppData\Local\.meteor` so it only had an install of meteor 1.5.2.2.
3. `choco install meteor`

**Result:** `'meteor' is not recognized as an internal or external command,
operable program or batch file.`  Meteor is only installed at `C:\Users\admin\AppData\Local\.meteor`

#### Attempt 5
1. after attempt 4 I tried copying the `1.6.0` folder from `C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool` to `C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.6.0`
2. modified `C:\Users\Bruce\AppData\Local\.meteor\meteor.bat` to point to the `1.6.0` folder

**Result**: copy failed.  It notified me that file names were too long for Windows.  When I tried to run `meteor` it failed trying to load a package that was not copied.

### Notes
Essentially, I want an install of 64 bit Windows 64 bit meteor to land here: `C:\Users\Bruce\AppData\Local\.meteor` instead of `C:\Users\admin\AppData\Local\.meteor`.

How can I make that happen?

**Comment by brucejo75** [comment]
# Workaround

- start `cmd` shell in "run as administrator" mode.
- in the command shell change 2 environment variables to your desired location:
```
set LOCALAPPDATA=C:\Users\<USERNAME>\AppData\Local
set USERPROFILE=C:\Users\<USERNAME>
```
- `choco install meteor`

## Result
meteor will install to `C:\Users\<USERNAME>\AppData\Local\.meteor` and all is good with the world!

**Comment by brucejo75** [comment]
Hi @abernix, moved the issue over to the correct repo.

Regarding https://github.com/meteor/meteor/issues/9288#issuecomment-341504189:
> Essentially, I want an install of 64 bit Windows 64 bit meteor to land here: C:\Users\Bruce\AppData\Local.meteor instead of C:\Users\admin\AppData\Local.meteor.

>This is the default behavior on Windows 10 for me, though admittedly I don't use cmd, but rather PowerShell. Do you have a different experience based on this factor? Also, since this seems specifically regarding the installer (and not a general Meteor + Windows problem), this seems like it would be best to open in an issue on the https://github.com/meteor/meteor-chocolatey-installer repository instead of here.

I did not try PowerShell.  My default behavior was that the install went to the admin user instead of the user that started the "run as administrator" `cmd` window.

Within that `cmd` window there are no vestiges of the original user.  Maybe that is an advantage of Powershell?

If Powershell works, it seems like there are a couple of possible solutions:
- document to use PowerShell only
- add a specific way to enable it for `cmd` window users.

**Comment by abernix** [comment]
Thanks for moving this!  Can you try PowerShell and see how it works for you?  I'm all for documenting it and there certainly might be a way to fix this correctly for `cmd`, but let's try to figure that out.  The installer code is all open source in this repository now so your help would be appreciated, though I will try to help get to the bottom of it too!

**Comment by brucejo75** [comment]
Installing with Powershell.

It still installed to `C:\Users\admin\AppData\Local\.meteor`.  I believe this is because I needed to "run as administrator", when I do this all the environment variables believe that I am the admin, not Bruce.
```
PS E:\> $Env:USERPROFILE
C:\Users\admin
PS E:\> $Env:LOCALAPPDATA
C:\Users\admin\AppData\Local
```

I can add `C:\Users\admin\AppData\Local\.meteor` to my path and meteor is found.  But I really want it all installed in my own User directory.

### Steps
1. made sure my environment was clean
- `choco uninstall meteor` (note: I needed to set the environment variables to point to my user AppData)
- remove chocolately, followed [these](https://chocolatey.org/docs/uninstallation) instructions.
2. reinstall chocolately with powershell.
- "run as adminstrator" `powershell.exe`
- follow instructions here.  Needed to `Set-ExecutionPolicy AllSigned`
- close powershell
3. install meteor
- "run as adminstrator" `powershell.exe`
- `choco install meteor`

### Expected
bits to install to `C:\Users\Bruce\AppData\Local\.meteor`

### Results
bits installed to `C:\Users\admin\AppData\Local\.meteor`
```
PS E:\> choco install meteor
Chocolatey v0.10.8
Installing the following packages:
meteor
By installing you accept licenses for the packages.

chocolatey-core.extension v1.3.3 [Approved]
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

meteor v0.0.1 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 100% - Completed download of C:\Users\admin\AppData\Local\Temp\chocolatey\meteor\0.0.1\meteor-bootstrap-os.win
dows.x86_64.tar.gz (140.52 MB).
Download of meteor-bootstrap-os.windows.x86_64.tar.gz (140.52 MB) completed.
Extracting C:\Users\admin\AppData\Local\Temp\chocolatey\meteor\0.0.1\meteor-bootstrap-os.windows.x86_64.tar.gz to C:\Use
rs\admin\AppData\Local\Temp\chocolatey\meteor\0.0.1...
C:\Users\admin\AppData\Local\Temp\chocolatey\meteor\0.0.1
Extracting C:\Users\admin\AppData\Local\Temp\chocolatey\meteor\0.0.1\meteor-bootstrap-os.windows.x86_64.tar to C:\Users\
admin\AppData\Local...
C:\Users\admin\AppData\Local
***************************************

Meteor has been installed!

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  https://docs.meteor.com

***************************************
 The install of meteor was successful.
  Software installed to 'C:\Users\admin\AppData\Local'

Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

### Recommend

The install script reads some setting that can redirect the install.

**Comment by abernix** [comment]
> I believe this is because I needed to "run as administrator", when I do this all the environment variables believe that I am the admin

This simply isn't the case for me in any of my PowerShell terminals when I "Run as an Administrator".

Researching, the first Google match for a similar problem points to a GitHub issue you yourself filed on another repository in April for the same problem: https://github.com/felixrieseberg/windows-build-tools/issues/54.

Is it possible your machine is misconfigured?

**Comment by brucejo75** [comment]
@abernix, thanks for following up!

Here is what I have:
### Environment
- Windows 10 1703 (OS Build 15063.674)
- account: `admin` account type: administrator
- account: `bruce` account type: standard user

### Repro
from account: `bruce`
1. right click windows Icon, select "Windows PowerShell (Admin)"
2. enter admin password into pop up dialog.
3. in powershell window enter `$Env:USERNAME`

Result: `admin`

This is the root of the problem.  Do you not see this same result?

**Comment by abernix** [comment]
Thanks for outlining the detail of the two separate accounts—that is an important detail.  As I stated already, I did not see that same result. I was using a single account which could escalate to admin-privileges within itself, not via switching to another user as it seems is the case when you escalate since your user account simply cannot escalate to admin.

I'll have to look at this after I've had an opportunity to setup a Windows box with that configuration, but I'm glad you've got a work-around for now.

**Comment by brucejo75** [comment]
Thanks for taking a look.  This the recommended way to run a Windows box, especially as a developer.  This will help keep attackers at bay that try to surreptitiously install SW on my box.

I rarely need to log in as admin and am conscious of all privilege elevations.

**Comment by abernix** [comment]
> This the recommended way to run a Windows box, especially as a developer.

I'm not sure what your reference is for that recommendation, but this seems subjective.  I do recall a time and place when the configuration you're outlining was possibly even mandatory, but from what I understand about Windows today (which I admit, is not as much as other OSes), [User Account Control (UAC)](https://en.wikipedia.org/wiki/User_Account_Control) was crafted, at least in part, to avoid this setup entirely and to "keep attackers at bay".

For what it's worth, according to Chocolatey, [the `meteor` package](https://chocolatey.org/packages/meteor/0.0.1) (version 0.0.1) has been installed 4500+ times and there are no other reports of this problem which I'm aware of.  I'm not trying to say that you're wrong for setting up your machine this way, and I'd like to support that configuration if it's possible, but from my perspective, I have to prioritize accordingly.

If you're willing to look into the problem, I'd really appreciate it, but be aware that I'm not presently willing to add the configuration option you're asking for.  Specifically because it's just not a usage pattern I see on any other Chocolatey packages and the installer was written to their specification.  Please do research further if you're able, it as I don't believe this is only a `meteor` package problem; I expect you'd run into this problem with other (many?) Chocolatey packages.

**Comment by brucejo75** [comment]
#### Standard User

> I'm not sure what your reference is for that recommendation, but this seems subjective. I do recall a time and place when the configuration you're outlining was possibly even mandatory, but from what I understand about Windows today (which I admit, is not as much as other OSes), User Account Control (UAC) was crafted, at least in part, to avoid this setup entirely and to "keep attackers at bay".

Yeah, I am a bit paranoid 😄 .

In a previous life I worked on the team at Microsoft that did "malware detection", "malicious software removal" and the data center deployment topology for the Office 365 email system front ends (AKA Exchange Information Protection ).  The things you see.

I also have a close friend that worked in Windows Update.  They are very busy.

I have always taken every precaution.

#### Priority
- I understand this is low priority because of the product signals you are seeing.

#### No info on Chocolately guidance

> Specifically because it's just not a usage pattern I see on any other Chocolatey packages and the installer was written to their specification. Please do research further if you're able, it as I don't believe this is only a meteor package problem; I expect you'd run into this problem with other (many?) Chocolatey packages.

You are right.  I looked at the Chocolately [Installation Paths](https://github.com/chocolatey/choco/wiki/CreatePackages#installation-paths) guidance and they do not warn about complications with using environment variables based on the user's name:
- `USERNAME`
- `USERPROFILE`
- `APPDATA`
- `LOCALAPPDATA`.

I will take it up with the Chocolately team and see what they say.

For now, the workaround works fine for me.

**Comment by bartmichu** [comment]
>  the meteor package (version 0.0.1) has been installed 4500+ times and there are no other reports of this problem which I'm aware of.

I do have the same issue on one of my machines, but it works well on other PC with very similar (if not the same) configuration. So far I wasn't able to narrow it down.
As to the number of reports personally I'm quite sure it's because most people are recklessly using privileged accounts and never get a chance to face this problem.

**Comment by arberg** [comment]
I fell over this issue, and I know a chocolatey thing not meteor. I just wanted to comment on the aspect of security. I think it might be relevant, since I found this topic by my Google-foo.

>abernix: I'm not sure what your reference is for that recommendation, but this seems subjective.

Here's a quote from current [Windows 10 documentation on Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works)

> **The UAC User Experience**
> When UAC is enabled, the user experience for standard users is different from that of administrators in Admin Approval Mode. The recommended and more secure method of running Windows 10 is to make your primary user account a standard user account. Running as a standard user helps to maximize security for a managed environment. 

Using choco install like this also worked for me with my standard user Alex when running powershell as Administrator
```
$Env:USERPROFILE="C:\users\Alex"
$Env:LOCALAPPDATA="${Env:USERPROFILE}\AppData\Local"
choco install <myapp>
```

**Comment by brucejo75** [comment]
**BTW**: I did enter a [PR for Chocolately documentation](https://github.com/chocolatey/choco-wiki/pull/73).  But I just noticed that it had not been integrated yet.

I just poked them again.

**Comment by arberg** [comment]
Ah great, thanks for the link.

**Comment by abernix** [comment]
@brucejo75 I realize that once you're probably installed and ready to go that you probably don't have to revisit this much, but did you come across anything that Meteor is doing wrong here?  It doesn't seem like I'm missing anything in Chocolatey's installation instructions, but do you know if we can still detect the _actual_ user when installing and install it to the right place? (And then put that install into the user's search `PATH`).  Would we be able to do that without `%LocalAppData%`?

When I was building the installer, I honestly didn't pay much attention because I assumed that `%LocalAppData%` would remain as the user but with administrative rights and as I stated previously, I only have a single user which I only use Administrative rights for as necessary.  In retrospect, I guess the escalated privileges for non-Admin users in Windows are not really "escalated", they're literally changing users. 🤷‍♂️

**Comment by brucejo75** [comment]
Hi @abernix,

- I am pretty much a happy WSL user now, just installing meteor on the Ubuntu subsystem. I barely touch windows when it comes to Meteor.
- The Chocolately folks are slow handling my PR. 😸 I am still poking them occasionally (I like resolution!).

I think when you "Run as Administrator" the identity transformation is pretty complete.  I could not find any environment variables that would give any clue to the identity of the invoking user. 😭

It is surprising that Chocolately had not solved this problem.  (e.g. run as regular user, grab identity parameters then "Run as Adminstrator")

I think the options are to document the [workaround](https://github.com/meteor/meteor-chocolatey-installer/issues/2#issuecomment-341508892) or handle it yourself.

For example, look for an environment variable that is specific to the Meteor install.  e.g.

```javascript
let username = METEOR_INSTALL_USERNAME || USERNAME;
// Error out if C:\Users\${username} or C:\Users\${username}\AppData\Local do not exist
```

Then derive the install location...

**Comment by evelant** [comment]
I just ran into this setting up a new laptop. Perhaps the meteor install documentation should at least reference this issue? The install method for windows seems totally broken since you can't run meteor as a normal user after following the instructions.

**Comment by filipenevola** [comment]
This installer is deprecated.

https://meteor.com/developers/install
