### ISSUE TITLE
Installation is Slow because of Anti-Virus like Windows Defender.

### ISSUE THREAD

**Issue by ruohki** [meteor/meteor-chocolatey-installer#5]
Hey,

having problems installing meteor on my system. Iam having the same issue as this one over at the meteor repo

meteor/meteor#9306

**Comment by abernix** [comment]
How long does it hang for?  Have you given it say, 20 minutes?  Longer?

Can you run `choco install meteor -y` with `--debug` and `--verbose` flags and provide the output?

**Comment by ruohki** [comment]
It managed to finish but took over an hour. Didnt expect it to take that long.
Gonna give it a shot on another machine with the debug flags tomorrow

**Comment by abernix** [comment]
Good to know!  When doing additional tests, please consider disabling Windows Defender (or any other virus scanner) since the performance is _vastly_ decreased when those are running due to the large number of unique files!

**Comment by nalbina** [comment]
This is a step back from the regular install mode. My installation is running on Win 10 Home with Chocolatey 0.10.8 for 1 and a half hours now without any indication whether it is finished or not.

**Comment by ruohki** [comment]
So i tried to install it on a fresh win10 pro box running the latest updates. 

I did a clean first time install of chocolatey and run the installer command. Yet it takes ages... Ill upload a gist with the ```--debug``` and ```--verbose``` log once its finished (oh everything is run in an administrator cmd)

**Comment by abernix** [comment]
Any updates on this, @ruohki?

**Comment by ruohki** [comment]
couldnt track the log because the console swallowed half of the output. Running it again right now on a freshly installed win 10 pro while piping the stuff into a file

edit: looks like its going to take a while again

Cocolatey Install Log:
https://gist.github.com/ruohki/3ccb6a6d6ba668b0808e8f20fcaa917b

Meteor Install Log:
https://gist.github.com/ruohki/7500ea4b9654d03b7b1d2e5dc41bc671

Installation took 20 min. He seemed to have a hard time on extracting the gz file and unpacking the tar took a great amount of time as well

**Comment by pcostarg** [comment]
I haven't played with meteor for a awhile and was astonished that the only official way is through Chocolatey. I don't use it. Then even after I installed chocolatey I had this hang forever, restarted multiple times because I believed it got stuck. I searched the logs and understood it was doing something, but taking a lot of time.

Then, after googling quite sometime, I took @abernix advice and disabled Windows Defender real time protection and boom! It got installed very quickly!

I have to say **this is very sloppy**. We expect installation to be a breeze and not get frustrated. msi installer was really good. I am not being against chocolatey, but I believe it should be just another installation method and not the only official method of installation.

**Comment by greenermoose** [comment]
Echo comments by @pcostarg. Turning off Windows Defender real time protection allows tar extraction to complete quickly. Otherwise, install script hangs and eventually times out.

**Comment by greenermoose** [comment]
My system is a Microsoft Surface Pro 3 with a clean install of Windows 10 Pro. Just wiped the system and wanted to reinstall meteor. Wasn't obvious that Windows Defender real time protection was running, but definitely was the culprit. As soon as that was turned off, chocolately install script completed. While Windows Defender was on, install script was hanging with no indication of progress.

**Comment by hwillson** [comment]
> Wasn't obvious that Windows Defender real time protection was running, but definitely was the culprit.

@abernix This is now happening frequently enough that I'm wondering if we should update the https://www.meteor.com/install instructions to mention this:

![screenshot 2017-12-04 06 31 58](https://user-images.githubusercontent.com/137740/33550717-ed6d50f8-d8bc-11e7-85ab-777d600e8332.png)

**Comment by abernix** [comment]
@hwillson Good call.  I've added this to my notes for some other homepage work I'm trying to get done soon.

**Comment by abernix** [comment]
I added this note to https://www.meteor.com/install some time ago, but it's still catching users off guard (understandably, as not everyone goes through that process) and causing them to invest time to figuring out what's going on, as @cinderblock reported was necessary recently in #1.

For obvious reasons, it might not be possible, but I ponder 🤔, through the glory of the installer, if we have the ability to add an exception for Meteor programmatically using the `Add-MpPreference` Cmdlet:

https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=win10-ps
http://wmug.co.uk/wmug/b/pwin/archive/2015/05/12/quickly-disable-windows-defender-on-windows-10-using-powershell

If any Windows users were able to figure this out for us, and ideally submit a PR to the installer, you'd likely make the experience even better for a lot of Windows users.  It's possible that adding the exception for `%LocalAppData%\.meteor` would not only improve the installation, but the subsequent _usage_ of `meteor` across the board.

**Comment by abernix** [comment]
Also, I know that Windows Defender is not the only pain point here, but as a very common vulnerability scanner, if we can detect it and respond accordingly, we _might_ target a majority (??) of users.

**Comment by sfthurber** [comment]
may i humbly suggest that meteor revert to a conventional installer. IMHO chocolatey is not worth the trouble.

**Comment by abernix** [comment]
@sfthurber Your comment comes without any substantiated reasoning for your declaration that it's "not worth the trouble".  The Chocolatey installer was created specifically to simplify maintenance for the Windows installer, which was difficult at best since it required Visual Studio, keeping the WiX libraries up to date, and a complicated certificate-signing procedure.

On the other hand, the Chocolatey installer found in this repository is simple to understand (a PowerShell script) and changes can be submitted by anyone in the community.  Rather than making suggestions which don't consider the full reasoning for why we made the switch, it would be helpful to identify and fix the problems, and I'd ask you to open new issues or add additional clarity to existing issues if you're having those problems.  Thanks!

**Comment by pcostarg** [comment]
@abernix I would respond with what I said before. There should be both options. First not everyone uses chocolatey and an msi is a standalone installer option. Secondly it can avoid this kind of issues we see with the anti virus. For me losing a couple of hours or more just to install when before it was a breeze does not seem like a good thing. Yes after we know what is happening it's an easy fix, but before it is an headache.

I wonder how many people wanted to try meteor and just gave up on uninstalling it because of this anti virus issue or even did not want to install another program, chocolatey.

The best option would be to have both msi install and chocolatey.

Well you maintain the project if you want to alienate some windows people is your choice.

**Comment by foobarbecue** [comment]
There should be a non-chocolately option. I don't use chocolatey for anything, and neither does anyone I know. The installation **of** chocolatey is messy and convoluted, and it causes this situation where you have to disable your antivirus to install meteor, which is actually impossible on many of my work machines due to sysadmin lockdown (with Symantec). Meteor used to be a cinch to install on windows, and now it's a non-starter. And actually, choco meteor install seems quite slow on the machine where I can disable windows defender, too. 

Edit after more thought: How about adding meteor releases to the Microsoft Store?

Edit after even more thought: if you're going to use a package manager, use conda! Lots of people have it installed anyway for anaconda, and it's cross-platform and the installation isn't janky like choco.

**Comment by foobarbecue** [comment]
I wanted to post this on the relevant issue ( #8139 ), but it's locked. Meteor sure is a pain to try and use on Windows.

![image](https://user-images.githubusercontent.com/854789/42137668-63f6df48-7d25-11e8-9c81-657be96d63a5.png)

**Comment by leosco** [comment]
I appreciate the technical issues associated with slowing down Meteor's installation through chocolatey because of anti-virus scanning the unique files during extraction, but this is a huge quality of life issue especially for machines under corporate compliance where you can't disable the anti-virus and are limited in their administrative capacity. 

@abernix I get that the .msi was a pain for you guys to maintain/certify, but it's still the gold standard for Windows installation, unfortunately, and it doesn't seem like there's a realistic workaround for this issue for computers that can't disable anti-virus. Not to mention, for most users, that's far from an ideal answer. Usually, most would consider it a red flag if you had to disable your anti-virus to install something. I know you guys made the decision to migrate to and completely embrace chocolatey, and having a package manager for Windows is great, but this issue for some users is going to be untenable and you're risking losing those users. I'm sure this is frustrating, Windows has sucked and been very unfriendly towards the Meteor platform for a long time.

Edit: not to mention the wide variety of other Windows-specific phantom issues, as well as insane discrepancies in performance between Mac/Linux and Windows versions of Meteor.

**Comment by abernix** [comment]
I think it's important that we don't mix up "slow install" with "dislike for Chocolatey" in the same issue, and "general performance" probably doesn't belong in this repository.

With regards to the topic that this issue relates to: The MSI installer was also quite slow and we used to recommend disabling anti-virus even when it was the only way to install on Windows.  I recall that, without anti-virus disabled, the MSI installer often took an hour to finish.

The Chocolatey installer is still extracting the same number of files, from the same archive, and unless it used some other underlying extraction API (which I think would be strange, no?), I don't understand why some of the experiences here are blaming the installer.   I'd like some more concrete comparisons if anyone was interested in making them.  I'm no expert here, but it seems strange that Chocolatey and corporate environments don't play more nicely together, particularly since [that's one of their value propositions](https://chocolatey.org/blog/chocolatey-business-and-professional-coming).

As a reminder, the installer only needs to run once, and after that `meteor` is self-updating, so if users can get over the initial installation hump with help from their IT department, Meteor should be all set and at the user's disposal.

Feedback on improving the situation is still very welcomed, but I'm afraid that moving back to an MSI installer is fairly unlikely based on our prior experiences.  In terms of something actionable which might help, I'm curious if anyone has thoughts about suggestions in https://github.com/meteor/meteor-chocolatey-installer/issues/5#issuecomment-374888903?

Lastly, in regards to general Windows performance (after installation), hopefully great work like that done by @zodern in https://github.com/meteor/meteor/pull/10399 will continue to boost Windows performance.

**Comment by pcostarg** [comment]
@abernix when I used the msi I never ever had to wait 1h. 10 to 15 minutes maximum, but usually less. So maybe you had some issues also and of course I might be the only one that msi was so fast (doubtful but still can be true).

I can only speak for myself but I never said to ditch Chocolatey. What I said is to give both options and giving back msi as an alternative might help a lot of people. Don't forget, also, that msi is a standalone installation that works directly within Windows. Chocolatey...well requires chocolatey to be installed first

I haven't installed meteor for a long time now so this might have changed. If you still want to go with only Chocolatey, maybe get more detailed information during installation. Like detailed progress indication so we know it is doing something and also acknowledging that if the process is slow people should consider temporarily disabling the anti virus and re-run the installation.

Once more, you maintain the project if you want to alienate some windows people is your choice.

**Comment by filipenevola** [comment]
This installer is deprecated.

https://meteor.com/developers/install
